CLANGPATH=~/mytools/llvm-3.2/bin/clang
OPTPATH=~/mytools/llvm-3.2/bin/opt

CLTRANSFORMPATH=$(PWD)/../ClTransform/bin/cltransform
CLINLINEPATH=$(PWD)/../ClInline/bin/clinline

SPIRTRANSFORMPATH=$(PWD)/../SpirTransform/lib/spirtransform.so

KERNELANALYSIS_SO_PATH=$(PWD)/../AnalysisPass/lib/klanalysis.so

KERNELEXPR_INCLUDE_PATH=$(PWD)/../LibKernelExpr/include
KERNELEXPR_LIB_PATH = $(PWD)/../LibKernelExpr/lib

SPIRHEADER=$(PWD)/src/opencl_spir.h

MKGR_INCLUDE_PATH=/home/phuchant/mytools/mkgr-1.2/include
MKGR_LIB_PATH=/home/phuchant/mytools/mkgr-1.2/lib

GLPK_LIB_PATH=/home/counilh/install_soft/glpk-4.55_install/lib/


USE_HWLOC=0
CUDA=1