CLANGPATH=~/mytools/llvm-5.0/bin/clang
CLANGVERSION=5.0.0
OPTPATH=~/mytools/llvm-5.0/bin/opt
LLVMLIBPATH=~/mytools/llvm-5.0/lib

CLTRANSFORMPATH=$(PWD)/../ClTransform/bin/cltransform
CLINLINEPATH=$(PWD)/../ClInline/bin/clinline

KERNELANALYSIS_SO_PATH=$(PWD)/../AnalysisPass/lib/klanalysis.so

KERNELEXPR_INCLUDE_PATH=$(PWD)/../LibKernelExpr/include
KERNELEXPR_LIB_PATH = $(PWD)/../LibKernelExpr/lib

MKGR_INCLUDE_PATH=/home/phuchant/mytools/mkgr-1.2/include
MKGR_LIB_PATH=/home/phuchant/mytools/mkgr-1.2/lib

GLPK_INCLUDE_PATH=/home/counilh/install_soft/glpk-4.55_install/include
GLPK_LIB_PATH=/home/counilh/install_soft/glpk-4.55_install/lib/


USE_HWLOC=1
CUDA=0